version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inktheory_postgres
    restart: always
    environment:
      POSTGRES_USER: inktheory
      POSTGRES_PASSWORD: inktheorypass
      POSTGRES_DB: inktheorydb
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
